en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Human Pangenome Reference Consortium."
  title: "Human Pangenome Reference Consortium"
  params:
    description: "Human Pangenome Reference Consortium"
    ### accessibility ###
    # accessibility:
    #   skip_text: "Skip to content"
    #   help_text: "Accessibility Statement"
    #   help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "Internal Wiki"
      link: "https://wiki.humanpangenome.org/"
    footer_cta:
      # text: "Contact Us"
      # link: "/contact-us/"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "#"
      weight: 1
    - identifier: "working-groups"
      name: "Working Groups"
      url: "/working-groups/"
      weight: 1
      parent: "about"
    - identifier: "release-timeline"
      name: "Release Timeline"
      url: "/release-timeline/"
      weight: 2
      # post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "about"
    - identifier: "funding"
      name: "Funding"
      url: "/funding/"
      weight: 3
      parent: "about"
    - identifier: "external-scientific-consultants"
      name: "External Scientific Consultants"
      url: "/external-scientific-consultants/"
      weight: 4
      parent: "about"
    - identifier: "associate-members"
      name: "Associate Members"
      url: "/associate-members/"
      weight: 5
      parent: "about"
    - identifier: "partners"
      name: "Partners"
      url: "/partners/"
      weight: 6
      parent: "about"
    - identifier: "code-of-conduct"
      name: "Code of Conduct"
      url: "/code-of-conduct/"
      weight: 7
      parent: "about"
    - identifier: "steering-committee"
      name: "Steering Committee"
      url: "/steering-committee/"
      weight: 8
      parent: "about"
    - identifier: "resources"
      name: "Resources"
      url: "#"
      weight: 2
    - identifier: "definitions"
      name: "Definitions"
      url: "/definitions/"
      weight: 1
      parent: "resources"
    - identifier: "data"
      name: "Data"
      url: "/data/"
      weight: 2
      parent: "resources"
    - identifier: "samples"
      name: "Samples"
      url: "/samples/"
      weight: 3
      parent: "resources"
    - identifier: "technology"
      name: "Technology"
      url: "/technology/"
      weight: 4
      parent: "resources"
    - identifier: "publications"
      name: "Publications"
      url: "/publications/"
      weight: 5
      parent: "resources"
    - identifier: "consent"
      name: "HPRC Consent"
      url: "/consent/"
      weight: 6
      parent: "resources"
    - identifier: "participant"
      name: "HPRC Participant"
      url: "https://hprc-participant.org/"
      weight: 7
      parent: "resources"
    # - identifier: "HPP"
    #   name: "HPP"
    #   url: "https://humanpangenomeproject.org/"
    #   weight: 3
    - identifier: "elsi"
      name: "ELSI"
      url: "#"
      weight: 3
    - identifier: "hprc-embedded-elsi"
      name: "HPRC Embedded ELSI"
      url: "/hprc-embedded-elsi/"
      weight: 1
      parent: "elsi"
    - identifier: "elsi-team"
      name: "ELSI team"
      url: "/elsi-team/"
      weight: 2
      parent: "elsi"
    - identifier: "contact"
      name: "Contact"
      url: "/contact/"
      weight: 4
    
    
# es:
#   languageName: Spanish
#   contentDir: content/es
#   weight: 2
#   title: "Título del Sitio"
#   params:
#     description: "Descripción del Sitio"
#   menu:
#     main:
#     - identifier: "about"
#       name: "Acerca de"
#       url: "/example-page/"
#       weight: 1
#     - identifier: "child-1"
#       name: "Página Hija de Ejemplo"
#       url: "/example-page/"
#       weight: 1
#       parent: "about"
#     - identifier: "faq"
#       name: "FAQs"
#       url: "/faq/"
#       weight: 3
#     - identifier: "blog"
      # name: "Blog"
      # url: "/blog/"
      # weight: 2
